version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pi-frontend-app:latest
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./AngularProyectoBack
      dockerfile: Dockerfile
    image: pi-backend-app:latest
    ports:
      - "9999:9999"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pi_bd
      - SPRING_DATASOURCE_USERNAME=root

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: pi_bd
    ports:
      - "3306:3306"